[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
exclude = ["debian*", "binaries*", "build*", "dist*"]

[project]
name = "test-bcpt"
version = "1.0.2"
dependencies = [
    "dfxml @ git+https://github.com/dfxml-working-group/dfxml_python",
    "prettytable>=3.9.0",
]
requires-python = ">=3.6"
authors = [
  {name = "Simson Garfinkel (simsong)"},
  {name = "Corey Forman (digitalsleuth)", email = "github@digitalsleuth.ca"},
]
maintainers = [
  {name = "Corey Forman (digitalsleuth)", email = "github@digitalsleuth.ca"},
]
description = "BitCurator python tools and scripts in an installable pip package"
readme = "README.md"
keywords = ["digital forensics", "dfir", "bitcurator", "bcc", "test-bcpt"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]

[project.urls]
Homepage = "https://github.com/kamwoods/test-bcpt"

[project.scripts]
identify-filenames = "test_bcpt.identify_filenames:main"
bulk-diff = "test_bcpt.bulk_diff:main"
build-stoplist = "test_bcpt.build_stoplist:main"
cda-tool = "test_bcpt.cda_tool:main"
cda2-tool = "test_bcpt.cda2_tool:main"
post-process-exif = "test_bcpt.post_process_exif:main"
